version: "3.8"

services:

    app:
        container_name: app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - network

    db:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432 #5433 (host - acesso de fora) : 5432 (container)
        networks:
            - network

    adminer:
        image: adminer
        container_name: admin
        restart: always
        ports:
            - 8085:8080
        networks:
            - network

volumes:
    db-data: ~

networks:
    network:
        driver: bridge